
  RuntimeError

  Poetry could not find a pyproject.toml file in /home/jimzer/Projects/BitsWired/bitswired or its parents

  at ~/.poetry/lib/poetry/_vendor/py3.9/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
