packageExtensions:
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"

  "next-sitemap@*":
    dependencies:
      "@next/env": "*"

  "react-spring@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "@visx/bounds@*":
    dependencies:
      react: "*"
      react-dom: "*"

  "@visx/xychart@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
