packageExtensions:
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
  "@emotion/styled-base@*":
    dependencies:
      "@emotion/react": "*"
  "@nestjs/graphql@*":
    dependencies:
      apollo-server-core: "*"
    peerDependencies:
      apollo-server-express: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/react": "*"
  apollo-engine-reporting-protobuf@^0.5:
    dependencies:
      "@apollo/protobufjs": ^1
      "@types/long": ^4
      long: ^4
  apollo-reporting-protobuf@^0.6:
    dependencies:
      "@types/long": ^4
      long: ^4
  typeorm@*:
    peerDependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
