version: "3.1"

services:
  postgres:
    image: postgres:alpine
    restart: "no"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: "no"
    ports:
      - "5001:5001"
    env_file: .env
