FROM node:lts-alpine

WORKDIR /bitswired.com

RUN yarn set version berry

COPY package.json .
COPY .yarn .
COPY yarn.lock .

RUN yarn plugin import workspace-tools

COPY .yarnrc.yml .

COPY packages/webapp packages/webapp

RUN yarn workspaces focus --all --production
RUN yarn add typescript

RUN yarn workspace @bitswired-web/webapp build
RUN yarn workspace @bitswired-web/webapp next export

CMD yarn workspace @bitswired-web/webapp start






